### ISSUE TITLE
Code missing from src/components/atoms

### ISSUE THREAD

**Issue by marexv** [CheesecakeLabs/ReactNativeCklExample#1]
Coming here from the [mentioned article](https://cheesecakelabs.com/br/blog/efficient-way-structure-react-native-projects/?utm_source=github) because "Enabling the use of the alias" part didn't work for me. 

Atoms (i.e code snippets) used in the article are not present in folders here.

Also code snippets used in the article might be wrong: 
```
import React from 'react';
import {HelloWorld} from '_atoms';

const App = () => ;

export default App;
```

should probably be:
```
import React from 'react';
import {HelloWorld} from '_atoms';

const App = () => <HelloWorld />;

export default App;
```

**Comment by helderburato** [comment]
Hi @marexv!

I appreciate your contact and you're right about this.
I will update in the article, thanks!  💯

**Comment by RowlandOti** [comment]
The aliases don't work. At least for Webstorm, how are you able to achieve this?
