### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by swalahamani** [CheesecakeLabs/ReactNativeCklExample#4]
Will the same structure work for TypeScript as well?

**Comment by helderburato** [comment]
> Will the same structure work for TypeScript as well?

You can use the same idea to structure the project the concepts will be the same.

To avoid the all effort about making eject from the initial CRA configurations I recommend you start a new RN project with TypeScript template and just create the structure based on this project structure.

**Comment by swalahamani** [comment]
Thanks @helderburato
